// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBmFnRabmSDU4fv2IwJ3eR8KJ5VkZ9k70M',
    appId: '1:285852592513:web:a6a431057f333e81a9a080',
    messagingSenderId: '285852592513',
    projectId: 'barberbook-6d6eb',
    authDomain: 'barberbook-6d6eb.firebaseapp.com',
    storageBucket: 'barberbook-6d6eb.firebasestorage.app',
    measurementId: 'G-HGPV3YYTN9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCq0sBFKFtHJOYm83QKSk6fSUd_GYwPCJM',
    appId: '1:285852592513:android:469686c330c68df2a9a080',
    messagingSenderId: '285852592513',
    projectId: 'barberbook-6d6eb',
    storageBucket: 'barberbook-6d6eb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDKTYAiAA7sdPCzJddSs50N3Gyh7z8NGm8',
    appId: '1:285852592513:ios:d47ecc230309a012a9a080',
    messagingSenderId: '285852592513',
    projectId: 'barberbook-6d6eb',
    storageBucket: 'barberbook-6d6eb.firebasestorage.app',
    iosBundleId: 'com.example.myapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDKTYAiAA7sdPCzJddSs50N3Gyh7z8NGm8',
    appId: '1:285852592513:ios:d47ecc230309a012a9a080',
    messagingSenderId: '285852592513',
    projectId: 'barberbook-6d6eb',
    storageBucket: 'barberbook-6d6eb.firebasestorage.app',
    iosBundleId: 'com.example.myapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBmFnRabmSDU4fv2IwJ3eR8KJ5VkZ9k70M',
    appId: '1:285852592513:web:279a8836aa54c811a9a080',
    messagingSenderId: '285852592513',
    projectId: 'barberbook-6d6eb',
    authDomain: 'barberbook-6d6eb.firebaseapp.com',
    storageBucket: 'barberbook-6d6eb.firebasestorage.app',
    measurementId: 'G-DNBKBTHE56',
  );
}
